#' BroadcastService 
#'
#' A delivery service through which content is provided via broadcast over the air or online. 
#'
#'
#' @param id identifier for the object (URI)
#' @param videoFormat (Text or Text or Text type.) The type of screening or video broadcast used (e.g. IMAX, 3D, SD, HD, etc.).
#' @param parentService (BroadcastService type.) A broadcast service to which the broadcast service may belong to such as regional variations of a national channel.
#' @param broadcaster (Organization type.) The organization owning or operating the broadcast service.
#' @param broadcastTimezone (Text type.) The timezone in [ISO 8601 format](http://en.wikipedia.org/wiki/ISO_8601) for which the service bases its broadcasts
#' @param broadcastDisplayName (Text type.) The name displayed in the channel guide. For many US affiliates, it is the network name.
#' @param broadcastAffiliateOf (Organization type.) The media network(s) whose content is broadcast on this station.
#' @param area (Place type.) The area within which users can expect to reach the broadcast service.
#' @param serviceType (Text type.) The type of service being offered, e.g. veterans' benefits, emergency relief, etc.
#' @param serviceOutput (Thing type.) The tangible thing generated by the service, e.g. a passport, permit, etc.
#' @param serviceAudience (Audience type.) The audience eligible for this service.
#' @param serviceArea (Place or GeoShape or AdministrativeArea or Place or GeoShape or AdministrativeArea or Place or GeoShape or AdministrativeArea type.) The geographic area where the service is provided.
#' @param review (Review or Review or Review or Review or Review or Review or Review or Review type.) A review of the item.
#' @param providerMobility (Text type.) Indicates the mobility of a provided service (e.g. 'static', 'dynamic').
#' @param provider (Person or Organization or Person or Organization or Person or Organization or Person or Organization or Person or Organization or Person or Organization type.) The service provider, service operator, or service performer; the goods producer. Another party (a seller) may offer those services or goods on behalf of the provider. A provider may also serve as the seller.
#' @param produces (Thing type.) The tangible thing generated by the service, e.g. a passport, permit, etc.
#' @param offers (Offer or Offer or Offer or Offer or Offer or Offer or Offer type.) An offer to provide this item&#x2014;for example, an offer to sell a product, rent the DVD of a movie, perform a service, or give away tickets to an event.
#' @param logo (URL or ImageObject or URL or ImageObject or URL or ImageObject or URL or ImageObject or URL or ImageObject type.) An associated logo.
#' @param isSimilarTo (Service or Product or Service or Product type.) A pointer to another, functionally similar product (or multiple products).
#' @param isRelatedTo (Service or Product or Service or Product type.) A pointer to another, somehow related product (or multiple products).
#' @param hoursAvailable (OpeningHoursSpecification or OpeningHoursSpecification or OpeningHoursSpecification type.) The hours during which this service or contact is available.
#' @param hasOfferCatalog (OfferCatalog or OfferCatalog or OfferCatalog type.) Indicates an OfferCatalog listing for this Organization, Person, or Service.
#' @param category (Thing or Text or Thing or Text or Thing or Text or Thing or Text type.) A category for the item. Greater signs or slashes can be used to informally indicate a category hierarchy.
#' @param broker (Person or Organization or Person or Organization or Person or Organization or Person or Organization type.) An entity that arranges for an exchange between a buyer and a seller.  In most cases a broker never acquires or releases ownership of a product or service involved in an exchange.  If it is not clear whether an entity is a broker, seller, or buyer, the latter two terms are preferred.
#' @param brand (Organization or Brand or Organization or Brand or Organization or Brand or Organization or Brand type.) The brand(s) associated with a product or service, or the brand(s) maintained by an organization or business person.
#' @param award (Text or Text or Text or Text or Text type.) An award won by or for this item.
#' @param availableChannel (ServiceChannel type.) A means of accessing the service (e.g. a phone bank, a web site, a location, etc.).
#' @param audience (Audience or Audience or Audience or Audience or Audience or Audience type.) An intended audience, i.e. a group for whom something was created.
#' @param areaServed (Text or Place or GeoShape or AdministrativeArea or Text or Place or GeoShape or AdministrativeArea or Text or Place or GeoShape or AdministrativeArea or Text or Place or GeoShape or AdministrativeArea or Text or Place or GeoShape or AdministrativeArea or Text or Place or GeoShape or AdministrativeArea type.) The geographic area where a service or offered item is provided.
#' @param aggregateRating (AggregateRating or AggregateRating or AggregateRating or AggregateRating or AggregateRating or AggregateRating or AggregateRating or AggregateRating type.) The overall rating, based on a collection of reviews or ratings, of the item.
#' @param url (URL type.) URL of the item.
#' @param sameAs (URL type.) URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.
#' @param potentialAction (Action type.) Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.
#' @param name (Text type.) The name of the item.
#' @param mainEntityOfPage (URL or CreativeWork type.) Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.
#' @param image (URL or ImageObject type.) An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].
#' @param identifier (URL or Text or PropertyValue type.) The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.
#' @param disambiguatingDescription (Text type.) A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.
#' @param description (Text type.) A description of the item.
#' @param alternateName (Text type.) An alias for the item.
#' @param additionalType (URL type.) An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. In RDFa syntax, it is better to use the native RDFa syntax - the 'typeof' attribute - for multiple types. Schema.org tools may have only weaker understanding of extra types, in particular those defined externally.
#'
#' @return a list object corresponding to a schema:BroadcastService
#'
#' @export

 BroadcastService <- function(id = NULL,
videoFormat = NULL,
 parentService = NULL,
 broadcaster = NULL,
 broadcastTimezone = NULL,
 broadcastDisplayName = NULL,
 broadcastAffiliateOf = NULL,
 area = NULL,
 serviceType = NULL,
 serviceOutput = NULL,
 serviceAudience = NULL,
 serviceArea = NULL,
 review = NULL,
 providerMobility = NULL,
 provider = NULL,
 produces = NULL,
 offers = NULL,
 logo = NULL,
 isSimilarTo = NULL,
 isRelatedTo = NULL,
 hoursAvailable = NULL,
 hasOfferCatalog = NULL,
 category = NULL,
 broker = NULL,
 brand = NULL,
 award = NULL,
 availableChannel = NULL,
 audience = NULL,
 areaServed = NULL,
 aggregateRating = NULL,
 url = NULL,
 sameAs = NULL,
 potentialAction = NULL,
 name = NULL,
 mainEntityOfPage = NULL,
 image = NULL,
 identifier = NULL,
 disambiguatingDescription = NULL,
 description = NULL,
 alternateName = NULL,
 additionalType = NULL){ 
Filter(Negate(is.null),
 list(
type = "BroadcastService",
id = id,
videoFormat = videoFormat,
parentService = parentService,
broadcaster = broadcaster,
broadcastTimezone = broadcastTimezone,
broadcastDisplayName = broadcastDisplayName,
broadcastAffiliateOf = broadcastAffiliateOf,
area = area,
serviceType = serviceType,
serviceOutput = serviceOutput,
serviceAudience = serviceAudience,
serviceArea = serviceArea,
review = review,
providerMobility = providerMobility,
provider = provider,
produces = produces,
offers = offers,
logo = logo,
isSimilarTo = isSimilarTo,
isRelatedTo = isRelatedTo,
hoursAvailable = hoursAvailable,
hasOfferCatalog = hasOfferCatalog,
category = category,
broker = broker,
brand = brand,
award = award,
availableChannel = availableChannel,
audience = audience,
areaServed = areaServed,
aggregateRating = aggregateRating,
url = url,
sameAs = sameAs,
potentialAction = potentialAction,
name = name,
mainEntityOfPage = mainEntityOfPage,
image = image,
identifier = identifier,
disambiguatingDescription = disambiguatingDescription,
description = description,
alternateName = alternateName,
additionalType = additionalType))}
